USE master
GO

ALTER DATABASE [db-name] SET EMERGENCY
GO

DBCC CHECKDB ( [db-name] )
GO

ALTER DATABASE [db-name] SET MULTI_USER
GO

ALTER DATABASE [db-name] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DBCC CHECKDB ([db-name], REPAIR_ALLOW_DATA_LOSS)
GO
